# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Clean White"
license = "Apache"
licenselink = "https://github.com/zhaohuabing/hugo-theme-cleanwhite/blob/master/LICENSE"
description = "A clean, elegant blog theme for hugo"
homepage = "https://github.com/zhaohuabing/hugo-theme-cleanwhite"
tags = [ "minimal", "responsive", "blog","light", "clean", "search"]
features = ["disqus", "site search", "responsive", "google analytics", "side bar"]
min_version = 0.30

[author]
  name = "Maks Manowski"
  homepage = "https://github.com/maksmanowski/wia-blog/themes/hugo-theme-wia"

# If porting an existing theme
[original]
  name = "Huabing Zhao"
  homepage = "https://github.com/zhaohuabing/hugo-theme-cleanwhite"
